apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Websockets Gateway
  description: Vanilla Websockets Gateway for the Reekoh IoT Platform. Allows hardware devices to connect to a Reekoh instance to communicate and send data via the Websocket Protocol
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - gateway
    - websockets
    
  loadBalancing:
    method: http
    enableSticky: true
  
  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      dataTopic:
        label: Data Topic
        type: String
        maxLength: 1000
        required: false
        default: data
        help: "(Optional) The topic type to listen to for sensor data. Default: data."
      commandTopic:
        label: Command Topic
        type: String
        maxLength: 1000
        required: false
        default: command
        help: "(Optional) The topic type to listen to for commands. Either for device or group of device. Default: commands."
